//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntelligentLevelEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IntelligentLevelEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap burger {
            get {
                object obj = ResourceManager.GetObject("burger", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap denpamen_body {
            get {
                object obj = ResourceManager.GetObject("denpamen_body", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap denpamen_head_00 {
            get {
                object obj = ResourceManager.GetObject("denpamen_head_00", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap denpamen_head_01 {
            get {
                object obj = ResourceManager.GetObject("denpamen_head_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap denpamen_head_02 {
            get {
                object obj = ResourceManager.GetObject("denpamen_head_02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap denpamen_head_03 {
            get {
                object obj = ResourceManager.GetObject("denpamen_head_03", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap denpamen_head_04 {
            get {
                object obj = ResourceManager.GetObject("denpamen_head_04", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap denpamen_head_05 {
            get {
                object obj = ResourceManager.GetObject("denpamen_head_05", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap denpamen_head_06 {
            get {
                object obj = ResourceManager.GetObject("denpamen_head_06", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap denpamen_head_07 {
            get {
                object obj = ResourceManager.GetObject("denpamen_head_07", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap denpamen_head_08 {
            get {
                object obj = ResourceManager.GetObject("denpamen_head_08", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap denpamen_head_09 {
            get {
                object obj = ResourceManager.GetObject("denpamen_head_09", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap denpamen_head_0A {
            get {
                object obj = ResourceManager.GetObject("denpamen_head_0A", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap denpamen_head_10 {
            get {
                object obj = ResourceManager.GetObject("denpamen_head_10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap denpamen_head_11 {
            get {
                object obj = ResourceManager.GetObject("denpamen_head_11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap denpamen_head_12 {
            get {
                object obj = ResourceManager.GetObject("denpamen_head_12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap denpamen_head_13 {
            get {
                object obj = ResourceManager.GetObject("denpamen_head_13", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap denpamen_head_14 {
            get {
                object obj = ResourceManager.GetObject("denpamen_head_14", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap denpamen_head_15 {
            get {
                object obj = ResourceManager.GetObject("denpamen_head_15", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap denpamen_head_16 {
            get {
                object obj = ResourceManager.GetObject("denpamen_head_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap denpamen_head_20 {
            get {
                object obj = ResourceManager.GetObject("denpamen_head_20", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap denpamen_head_21 {
            get {
                object obj = ResourceManager.GetObject("denpamen_head_21", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap denpamen_head_22 {
            get {
                object obj = ResourceManager.GetObject("denpamen_head_22", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap denpamen_head_23 {
            get {
                object obj = ResourceManager.GetObject("denpamen_head_23", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap denpamen_head_24 {
            get {
                object obj = ResourceManager.GetObject("denpamen_head_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap denpamen_head_25 {
            get {
                object obj = ResourceManager.GetObject("denpamen_head_25", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flag_eu {
            get {
                object obj = ResourceManager.GetObject("flag_eu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flag_jp {
            get {
                object obj = ResourceManager.GetObject("flag_jp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flag_us {
            get {
                object obj = ResourceManager.GetObject("flag_us", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ico_arrow_down {
            get {
                object obj = ResourceManager.GetObject("ico_arrow_down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ico_arrow_left {
            get {
                object obj = ResourceManager.GetObject("ico_arrow_left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ico_arrow_right {
            get {
                object obj = ResourceManager.GetObject("ico_arrow_right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ico_arrow_up {
            get {
                object obj = ResourceManager.GetObject("ico_arrow_up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ico_barcode2d {
            get {
                object obj = ResourceManager.GetObject("ico_barcode2d", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ico_bin_closed {
            get {
                object obj = ResourceManager.GetObject("ico_bin_closed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ico_disk {
            get {
                object obj = ResourceManager.GetObject("ico_disk", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ico_door_blue {
            get {
                object obj = ResourceManager.GetObject("ico_door_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ico_door_in {
            get {
                object obj = ResourceManager.GetObject("ico_door_in", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ico_door_red {
            get {
                object obj = ResourceManager.GetObject("ico_door_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ico_door_yellow {
            get {
                object obj = ResourceManager.GetObject("ico_door_yellow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ico_folder {
            get {
                object obj = ResourceManager.GetObject("ico_folder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ico_folder_picture {
            get {
                object obj = ResourceManager.GetObject("ico_folder_picture", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ico_grid {
            get {
                object obj = ResourceManager.GetObject("ico_grid", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ico_ladder_blue {
            get {
                object obj = ResourceManager.GetObject("ico_ladder_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ico_ladder_green {
            get {
                object obj = ResourceManager.GetObject("ico_ladder_green", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ico_ladder_purple {
            get {
                object obj = ResourceManager.GetObject("ico_ladder_purple", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ico_ladder_red {
            get {
                object obj = ResourceManager.GetObject("ico_ladder_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ico_ladder_yellow {
            get {
                object obj = ResourceManager.GetObject("ico_ladder_yellow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ico_layout_content {
            get {
                object obj = ResourceManager.GetObject("ico_layout_content", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ico_lock {
            get {
                object obj = ResourceManager.GetObject("ico_lock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ico_magnifier {
            get {
                object obj = ResourceManager.GetObject("ico_magnifier", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ico_page_white {
            get {
                object obj = ResourceManager.GetObject("ico_page_white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ico_page_white_copy {
            get {
                object obj = ResourceManager.GetObject("ico_page_white_copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ico_palette {
            get {
                object obj = ResourceManager.GetObject("ico_palette", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ico_switch_down {
            get {
                object obj = ResourceManager.GetObject("ico_switch_down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ico_switch_left {
            get {
                object obj = ResourceManager.GetObject("ico_switch_left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ico_switch_right {
            get {
                object obj = ResourceManager.GetObject("ico_switch_right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ico_switch_up {
            get {
                object obj = ResourceManager.GetObject("ico_switch_up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ico_transparent {
            get {
                object obj = ResourceManager.GetObject("ico_transparent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_star_light {
            get {
                object obj = ResourceManager.GetObject("icon_star_light", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_star_yellow {
            get {
                object obj = ResourceManager.GetObject("icon_star_yellow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pushmoPalette {
            get {
                object obj = ResourceManager.GetObject("pushmoPalette", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pyramids_back1 {
            get {
                object obj = ResourceManager.GetObject("pyramids_back1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pyramids_back2 {
            get {
                object obj = ResourceManager.GetObject("pyramids_back2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pyramids_back3 {
            get {
                object obj = ResourceManager.GetObject("pyramids_back3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pyramids_back4 {
            get {
                object obj = ResourceManager.GetObject("pyramids_back4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pyramids_back5 {
            get {
                object obj = ResourceManager.GetObject("pyramids_back5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pyramids_logo {
            get {
                object obj = ResourceManager.GetObject("pyramids_logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pyramids_sprite_00 {
            get {
                object obj = ResourceManager.GetObject("pyramids_sprite_00", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pyramids_sprite_01 {
            get {
                object obj = ResourceManager.GetObject("pyramids_sprite_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pyramids_sprite_02 {
            get {
                object obj = ResourceManager.GetObject("pyramids_sprite_02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pyramids_sprite_03 {
            get {
                object obj = ResourceManager.GetObject("pyramids_sprite_03", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pyramids_sprite_04 {
            get {
                object obj = ResourceManager.GetObject("pyramids_sprite_04", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pyramids_sprite_05 {
            get {
                object obj = ResourceManager.GetObject("pyramids_sprite_05", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pyramids_sprite_06 {
            get {
                object obj = ResourceManager.GetObject("pyramids_sprite_06", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pyramids_sprite_07 {
            get {
                object obj = ResourceManager.GetObject("pyramids_sprite_07", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pyramids_sprite_08 {
            get {
                object obj = ResourceManager.GetObject("pyramids_sprite_08", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pyramids_sprite_09 {
            get {
                object obj = ResourceManager.GetObject("pyramids_sprite_09", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pyramids_sprite_0A {
            get {
                object obj = ResourceManager.GetObject("pyramids_sprite_0A", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pyramids_sprite_0B {
            get {
                object obj = ResourceManager.GetObject("pyramids_sprite_0B", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pyramids_sprite_0C {
            get {
                object obj = ResourceManager.GetObject("pyramids_sprite_0C", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pyramids_sprite_0D {
            get {
                object obj = ResourceManager.GetObject("pyramids_sprite_0D", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pyramids_sprite_0E {
            get {
                object obj = ResourceManager.GetObject("pyramids_sprite_0E", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pyramids_sprite_0F {
            get {
                object obj = ResourceManager.GetObject("pyramids_sprite_0F", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pyramids_sprite_10 {
            get {
                object obj = ResourceManager.GetObject("pyramids_sprite_10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pyramids_sprite_11 {
            get {
                object obj = ResourceManager.GetObject("pyramids_sprite_11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pyramids_sprite_12 {
            get {
                object obj = ResourceManager.GetObject("pyramids_sprite_12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pyramids_sprite_13 {
            get {
                object obj = ResourceManager.GetObject("pyramids_sprite_13", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pyramids_sprite_14 {
            get {
                object obj = ResourceManager.GetObject("pyramids_sprite_14", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pyramids_sprite_15 {
            get {
                object obj = ResourceManager.GetObject("pyramids_sprite_15", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pyramids_sprite_16 {
            get {
                object obj = ResourceManager.GetObject("pyramids_sprite_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pyramids_sprite_17 {
            get {
                object obj = ResourceManager.GetObject("pyramids_sprite_17", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pyramids_sprite_18 {
            get {
                object obj = ResourceManager.GetObject("pyramids_sprite_18", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pyramids_sprite_19 {
            get {
                object obj = ResourceManager.GetObject("pyramids_sprite_19", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pyramids_sprite_1A {
            get {
                object obj = ResourceManager.GetObject("pyramids_sprite_1A", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pyramids_sprite_1B {
            get {
                object obj = ResourceManager.GetObject("pyramids_sprite_1B", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pyramids_sprite_1C {
            get {
                object obj = ResourceManager.GetObject("pyramids_sprite_1C", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pyramids_sprite_1D {
            get {
                object obj = ResourceManager.GetObject("pyramids_sprite_1D", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pyramids_sprite_1E {
            get {
                object obj = ResourceManager.GetObject("pyramids_sprite_1E", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pyramids_sprite_1F {
            get {
                object obj = ResourceManager.GetObject("pyramids_sprite_1F", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pyramids_sprite_20 {
            get {
                object obj = ResourceManager.GetObject("pyramids_sprite_20", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pyramids_sprite_21 {
            get {
                object obj = ResourceManager.GetObject("pyramids_sprite_21", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pyramids_sprite_22 {
            get {
                object obj = ResourceManager.GetObject("pyramids_sprite_22", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pyramids_sprite_23 {
            get {
                object obj = ResourceManager.GetObject("pyramids_sprite_23", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pyramids_sprite_24 {
            get {
                object obj = ResourceManager.GetObject("pyramids_sprite_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pyramids_sprite_25 {
            get {
                object obj = ResourceManager.GetObject("pyramids_sprite_25", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pyramids_sprite_26 {
            get {
                object obj = ResourceManager.GetObject("pyramids_sprite_26", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pyramids_sprite_27 {
            get {
                object obj = ResourceManager.GetObject("pyramids_sprite_27", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pyramids_sprite_28 {
            get {
                object obj = ResourceManager.GetObject("pyramids_sprite_28", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pyramids_sprite_29 {
            get {
                object obj = ResourceManager.GetObject("pyramids_sprite_29", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pyramids_sprite_2A {
            get {
                object obj = ResourceManager.GetObject("pyramids_sprite_2A", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pyramids_sprite_2B {
            get {
                object obj = ResourceManager.GetObject("pyramids_sprite_2B", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pyramids_sprite_2C {
            get {
                object obj = ResourceManager.GetObject("pyramids_sprite_2C", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pyramids_sprite_2D {
            get {
                object obj = ResourceManager.GetObject("pyramids_sprite_2D", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pyramids_sprite_2E {
            get {
                object obj = ResourceManager.GetObject("pyramids_sprite_2E", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pyramids_sprite_2F {
            get {
                object obj = ResourceManager.GetObject("pyramids_sprite_2F", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pyramids_sprite_30 {
            get {
                object obj = ResourceManager.GetObject("pyramids_sprite_30", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pyramids_sprite_31 {
            get {
                object obj = ResourceManager.GetObject("pyramids_sprite_31", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pyramids_sprite_32 {
            get {
                object obj = ResourceManager.GetObject("pyramids_sprite_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pyramids_sprite_33 {
            get {
                object obj = ResourceManager.GetObject("pyramids_sprite_33", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sprite_cloud {
            get {
                object obj = ResourceManager.GetObject("sprite_cloud", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sprite_door_blue {
            get {
                object obj = ResourceManager.GetObject("sprite_door_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sprite_door_red {
            get {
                object obj = ResourceManager.GetObject("sprite_door_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sprite_door_yellow {
            get {
                object obj = ResourceManager.GetObject("sprite_door_yellow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sprite_flag {
            get {
                object obj = ResourceManager.GetObject("sprite_flag", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sprite_ladder_blue {
            get {
                object obj = ResourceManager.GetObject("sprite_ladder_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sprite_ladder_green {
            get {
                object obj = ResourceManager.GetObject("sprite_ladder_green", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sprite_ladder_purple {
            get {
                object obj = ResourceManager.GetObject("sprite_ladder_purple", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sprite_ladder_red {
            get {
                object obj = ResourceManager.GetObject("sprite_ladder_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sprite_ladder_yellow {
            get {
                object obj = ResourceManager.GetObject("sprite_ladder_yellow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sprite_switch_down {
            get {
                object obj = ResourceManager.GetObject("sprite_switch_down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sprite_switch_left {
            get {
                object obj = ResourceManager.GetObject("sprite_switch_left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sprite_switch_right {
            get {
                object obj = ResourceManager.GetObject("sprite_switch_right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sprite_switch_trans {
            get {
                object obj = ResourceManager.GetObject("sprite_switch_trans", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sprite_switch_up {
            get {
                object obj = ResourceManager.GetObject("sprite_switch_up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap strawberry {
            get {
                object obj = ResourceManager.GetObject("strawberry", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tool_cloud {
            get {
                object obj = ResourceManager.GetObject("tool_cloud", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tool_door {
            get {
                object obj = ResourceManager.GetObject("tool_door", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tool_fill {
            get {
                object obj = ResourceManager.GetObject("tool_fill", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tool_flag {
            get {
                object obj = ResourceManager.GetObject("tool_flag", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tool_import {
            get {
                object obj = ResourceManager.GetObject("tool_import", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tool_manhole {
            get {
                object obj = ResourceManager.GetObject("tool_manhole", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tool_pencil {
            get {
                object obj = ResourceManager.GetObject("tool_pencil", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tool_pipette {
            get {
                object obj = ResourceManager.GetObject("tool_pipette", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tool_switch {
            get {
                object obj = ResourceManager.GetObject("tool_switch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
